name: starlink
# This package is not intended to be published
publish_to: none
description: >
  This package contains classes to define Starlink data structures:
  https://api.spacexdata.com/v4/starlink
environment:
  sdk: '>=2.12.0 <4.0.0'
dependencies:
  dart_json_mapper:
dev_dependencies:
  build_runner:
dependency_overrides:
  dart_json_mapper:
    path: ../../mapper