name: dart_json_mapper_fixnum
version: 1.1.2
description: >
  This is a dart-json-mapper complementary package
  provides support for https://pub.dev/packages/fixnum types in order to
  serialize / deserialize them from / to JSON.
homepage: https://github.com/k-paxian/dart-json-mapper/tree/master/adapters/fixnum
environment:
  sdk: '>=2.3.1 <3.0.0'
dependencies:
  dart_json_mapper: '>=1.5.6 <3.0.0'
  fixnum: ^0.10.11
dev_dependencies:
  pedantic:
  build_runner:
  build_test:
  test:
#dependency_overrides:
#  dart_json_mapper:
#    path: ../../mapper