name: dart_json_mapper_mobx
version: 2.0.5
description: >
  This is a dart-json-mapper complementary package
  provides support for MobX Stores to persist as JSON.
homepage: https://github.com/k-paxian/dart-json-mapper/tree/master/adapters/mobx
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  dart_json_mapper: '>=2.1.12 <3.0.0'
  mobx: ^2.0.7
dev_dependencies:
  mobx_codegen:
  reflectable:
  lints:
  build_runner:
  build_test:
  test:
#dependency_overrides:
#  dart_json_mapper:
#    path: ../../mapper
