name: dart_json_mapper
version: 1.7.7
description: >
  This package allows programmers to annotate Dart objects in order to
  serialize / deserialize them from / to JSON.
homepage: https://github.com/k-paxian/dart-json-mapper
environment:
  sdk: '>=2.6.1 <3.0.0'
dependencies:
  analyzer: '>=0.40.3 <=0.50.4'
  build: ^1.5.0
  intl: ^0.16.1
  reflectable: ^2.2.8
dev_dependencies:
  pedantic:
  build_runner:
  build_test:
  test:
