name: dart_json_mapper
version: 2.2.16
description: >
  This package allows programmers to annotate Dart objects in order to
  serialize / deserialize them from / to JSON.
homepage: https://github.com/k-paxian/dart-json-mapper
environment:
  sdk: '>=2.17.0 <4.0.0'
dependencies:
  analyzer: ^6.8.0
  build: ^2.4.1
  build_config: ^1.1.1
  intl: ^0.20.2
  meta: ^1.16.0
  path: ^1.8.3
  reflectable: ^4.0.12
  collection: ^1.18.0
  pubspec_parse: ^1.3.0
dev_dependencies:
  lints:
  build_runner:
