name: performance_test
version: 0.0.0
description: >
  This package contains performance tests for the following JSON interoperability libraries:
  - JsonSerializable https://pub.dev/packages/json_serializable
  - BuiltValue https://pub.dev/packages/built_value
  - DartJsonMapper https://pub.dev/packages/dart_json_mapper
environment:
  sdk: '>=2.6.1 <3.0.0'
dependencies:
  dart_json_mapper:
  json_annotation: 3.0.1
  built_value: 7.1.0
  intl: ^0.16.1
dev_dependencies:
  json_serializable: 3.3.0
  built_value_generator: ^7.1.0
  pedantic:
  build_runner:
  build_test:
  test:
dependency_overrides:
  dart_json_mapper:
    path: ../mapper